### ISSUE TITLE
Data availability

### ISSUE THREAD

**Issue by nalinimsingh** [bryanhe/CloudPred#1]
Hi,

I enjoyed this paper and was hoping to play around with the simulation platform. I think the `scripts/run_all.sh` script is currently missing, so I tried to first run `scripts/synthetic.py.` That script seems to rely on npz fils in a `data` folder not included in the repo, with the real scRNA-seq from the 10 different cell types. Is this data publicly available?

Thanks,
Nalini

**Comment by bryanhe** [comment]
`scripts/run_all.sh` and `data/purified` should be added now.

**Comment by nalinimsingh** [comment]
Awesome, thanks!
